add exit code safeguard to nodejs ci-cd, add the full python ci-cd

diff --git a/nodejs/ci-cd.yml b/nodejs/ci-cd.yml
--- a/nodejs/ci-cd.yml
+++ b/nodejs/ci-cd.yml
@@ -103,14 +103,17 @@ jobs:
       - name: Install dependencies
         run: |
           npm ci --loglevel verbose 2>&1 | tee logs/install.log
+          exit ${PIPESTATUS[0]} # without this explicit exit code return, even if the previous command fails, the step won't return error because of 'tee'
 
       - name: Build the app
         run: |
           npm run build --if-present --loglevel verbose 2>&1 | tee logs/build.log
+          exit ${PIPESTATUS[0]}
 
       - name: Run tests
         run: |
           npm test --loglevel verbose 2>&1 | tee logs/test.log
+          exit ${PIPESTATUS[0]}
 
       # Artifact publish to pipeline
 
@@ -171,8 +174,12 @@ jobs:
       #     START_LINE=$(( $( grep -n "## $RELEASE_TAG" CHANGELOG.md | grep -Eo '^[^:]+' ) + 2 ))
       #     END_LINE=$(( $( grep -n "## $PREVIOUS_TAG" CHANGELOG.md | grep -Eo '^[^:]+' ) - 2 ))
       #     RELEASE_NOTES=$(echo $'### Changelog:\n\n' "$( sed -n "$START_LINE,$END_LINE"p CHANGELOG.md )")
+      #     RELEASE_ASSETS="" # list the relative paths to the files separated by a single space
 
-      #     gh release create $RELEASE_TAG --title $RELEASE_TITLE --notes "$RELEASE_NOTES"
+      #     gh release create $RELEASE_TAG \
+      #     --title $RELEASE_TITLE \
+      #     --notes "$RELEASE_NOTES" \
+      #     $RELEASE_ASSETS
       #   env:
       #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
